#+TITLE:      Slencer
#+SUBTITLE:  Fictions and pure FOH domain reasonings  
#+AUTHOR:     son0p (Federico López)
#+EMAIL:      fede2001@gmail.com
#+INFOJS_OPT: view:t toc:t ltoc:t mouse:underline buttons:0y path:http://thomasf.github.io/solarized-css/org-info.min.js
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://bootswatch.com/4/slate/bootstrap.min.css" />
#+OPTIONS:    H:3 num:nil  \n:nil ::t |:t ^:t -:t f:t *:t tex:t  tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+CATEGORY:   communication
#+CONSTANTS: pi=3.14159265358979323846


** About
A pseudo language for structured knowledge about FOH (Front of House) audio and mental activities.

Inspired by:

http://r-s-g.org/LCL/controlstructure.html

https://jeremywsherman.com/blog/2015/10/10/idris-metaprogramming-hello-world/

Disclaimer: mainly broken english.


** Data Types
   *audioStream*

   Finite(?) duration flux of analog or digital audio signal related to an event, writable by /operators/, /controlStream/, /soundGenerator/, readable by /spectator/, /blackhole/, /feedback/, /musicalError/, /glith/

   *controlStream*

   Finite flux of data intended to operate over an /audioStream/


*group*



Non empty set with at least one internal operation (addition), and an inverse element (mute). ¿can be associative?

*spectactor*

    Animated acoustic absorbers, readable as /audioStream/

*crew*

    Humans with different talents organized in a hierarchical system

- roadies: //audioStream// guards

- production manager: can block or unblock master /audioStream/, conector with in-situ provider of audio tools

*audioChain*

*blackHole*

    Receptor of an /audioStream/ inaudible to spectators. eg: /audioStream/ <helpMic>

*dinamicRange* 

*coberture*

*lowFreqDispertion*

Acoustic densities fenomenology at south of the spectrum, noticeable on the skin

*audioSpots*
   
 Geolocable zones valuable as  acoustic-turist attraction

- powerAlley:     Corridor not suitable for people sensible to lowFreqDispertion

*stageLekage*

*bus*

*matrix*

*subGroup*

Consolidate operable /audioStream/s

*VCA*

Execute domain in /audioStream/(s)  level(s) via controlStream

*glitch*

*feedback*

Recursive induction of self /audioStream/ where the amplified version of the /audioStream/ surpass the source /audioStream/.

*musicalError*

Fluctuations of expected musical conventions. 

*userCookies*

*importance*

Subjetive valoration  writable by /audioStream/, controlStream, spectator, manager, etc

*moneyChannel*

/audioStream/ whith highest importance calculated by spectator, manager, and soloist.

*Reactionist*

Entity that use the reaction as their main behavior, do not take the time to reflect on the situation, Real time utility. 

*identityElement*

All pass entity, information can be grabbed from it.
    
** Operators
*mix*

    Add or subtrac  importance in /audioStream/s

*append*

    Create a new /audioStream/ at the end of a /list/

*process*

    An instance who execute instructions and can have multiple threads who can be concurrent.

*mute*

    The art of kill an /audioStream/

*route*

    Set up statics routes to specific ports, host, networks, readable by /audioStream/

*duplicate*

*align*

*unAlign*

*equalize*

*deformFrequencyResponse*

*deformTimeResponse*

*distract*

** Control structures

*gainStructure*

    Aim to preserve the dinamicRange in an audioChain

*compress*

*expand*

*compensate*

*panic [boolean]*

    When TRUE, trigger a priority on moneyChannel and apply force to make everthing else ignorable.

*Environment Variables*

-Initialization: For each new state is required to operator to initialize the value of participant variables, in decreasing importances until time avaliable is extingished

*Score*

    Graphical representation of how an environment evolves in time

*Resiliense*

** Functions
*** contextConformation
*** Monitor Network bootstrap

#+BEGIN_SRC R
     allMixes <- pinkNoise homogeneous distribution  
     -10db %>% all audioStreams %>% all mixes
      focal subject <- 0db 
#+END_SRC

*** contextTransformation
*** highlight
*** mask
*** backendBlurr
*** moneyChannel
*** faderRide
*** mutilate
*** manyToOne / oneToMany

    Transit between distant sources and near sources.ej: disturb the balance between room mics and short field mics in a drumkit. / functions on master bus.

*** reSignificate

    Momentary or permanent use of abnormal balance contrary to common sense.

*** southArt

    Any sofisticated use of entitys below 80hz

*** snakeAlucination

    In homenage to the people who occupy the strait line between the FOH and stage, stereo extravagances.

*** dualMono
*** heyMister

    Abandonation of the console in order to respond a distract query of a spectator

*** belowRadar

    Find the minimun level of a entity

*** eliminateComparison
*** fastBuildUp
*** watchDog

    DinamicRange survelliance in search of rules violators, can eat userCookies 
*** prepareForNext
    for each Evironment Variable 
      do initialize until avaliable time end
*** scoreReader

    Dictates next highlight in a time series score
    while( time state rolling )
      eval time
        query next highlight
          call operator attention 
            cue call bar countdown
*** errorTail
    Must activate resiliense tools to recover concentration

** test
*Survey your tools

*Tactic functions

*Filling a hole
